/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataValidation;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author ethankraus
 */
public class DataValidation extends javax.swing.JFrame {

    /**
     * Creates new form DataValidation
     */
    public DataValidation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SmartIDButton = new javax.swing.JRadioButton();
        PassportButton = new javax.swing.JRadioButton();
        IDNumberField = new javax.swing.JTextField();
        AgeField = new javax.swing.JTextField();
        DateField = new javax.swing.JTextField();
        EnterButton = new javax.swing.JButton();
        IDNumberCheck = new javax.swing.JCheckBox();
        AgeCheck = new javax.swing.JCheckBox();
        DateCheck = new javax.swing.JCheckBox();
        BookingCheck = new javax.swing.JCheckBox();
        IDNumberExplanation = new javax.swing.JLabel();
        AgeExplanation = new javax.swing.JLabel();
        DateExplanation = new javax.swing.JLabel();
        BookingExplanation = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATA VALIDATION");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setText("Home Affairs");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 6, -1, -1));

        jLabel2.setText("ID Number:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, -1, -1));

        jLabel3.setText("Age:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, -1, -1));

        jLabel4.setText("Date(dd/mm/yyyy):");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, -1, -1));

        jLabel5.setText("Booking Type:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 192, -1, -1));

        buttonGroup1.add(SmartIDButton);
        SmartIDButton.setText("SmartID");
        jPanel2.add(SmartIDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 188, -1, -1));

        buttonGroup1.add(PassportButton);
        PassportButton.setText("Passport");
        jPanel2.add(PassportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 217, -1, -1));
        jPanel2.add(IDNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 54, 140, -1));
        jPanel2.add(AgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 98, 140, -1));
        jPanel2.add(DateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 140, -1));

        EnterButton.setText("ENTER");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(EnterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 253, -1, -1));
        jPanel2.add(IDNumberCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));
        jPanel2.add(AgeCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));
        jPanel2.add(DateCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));
        jPanel2.add(BookingCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));
        jPanel2.add(IDNumberExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 210, 20));
        jPanel2.add(AgeExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));
        jPanel2.add(DateExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));
        jPanel2.add(BookingExplanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 280));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed

        if (IDNumberField.getText().matches("\\d+") && IDNumberField.getText().length() == 13) {
            IDNumberField.setBorder(new LineBorder(Color.GREEN));
            IDNumberCheck.setSelected(true);
            IDNumberCheck.setText("Valid");
            IDNumberExplanation.setText("");
        } else {
            IDNumberField.setBorder(new LineBorder(Color.RED));
            IDNumberCheck.setSelected(false);
            IDNumberCheck.setText("Invalid");
            if (IDNumberField.getText().matches("\\d+") && IDNumberField.getText().length() > 13) {
                IDNumberExplanation.setText("Over 13 numbers");
            } else {
                if (IDNumberField.getText().isEmpty()) {
                    IDNumberExplanation.setText("enter your ID");
                } else {
                    if (IDNumberField.getText().matches("\\d+") && IDNumberField.getText().length() < 13) {
                        IDNumberExplanation.setText("Under 13 numbers");
                    } else {
                        IDNumberExplanation.setText("Only numbers are valid");
                    }
                }
            }
        }

        if (AgeField.getText().matches("\\d+")) {
            AgeField.setBorder(new LineBorder(Color.GREEN));
            AgeCheck.setSelected(true);
            AgeCheck.setText("Valid");
            AgeExplanation.setText("");
        } else {
            AgeField.setBorder(new LineBorder(Color.RED));
            AgeCheck.setSelected(false);
            AgeCheck.setText("Invalid");

            if (AgeField.getText().isEmpty()) {
                AgeExplanation.setText("enter your Age");
            } else {
                if (!(AgeField.getText().matches("\\d+"))) {
                    AgeExplanation.setText("Only numbers are valid");
                }
            }
        }

        if (DateField.getText().isEmpty()) {
            DateField.setBorder(new LineBorder(Color.RED));
            DateCheck.setSelected(false);
            DateCheck.setText("Invalid");
            DateExplanation.setText("No Date has been entered");
        } else {
            if (!(DateField.getText().length() == 10)) {
                DateField.setBorder(new LineBorder(Color.RED));
                DateCheck.setSelected(false);
                DateCheck.setText("Invalid");
                DateExplanation.setText("Incorrect format for date");
            } else {
                if (!(Integer.parseInt("" + DateField.getText().charAt(3) + DateField.getText().charAt(4)) <= 12 && Integer.parseInt("" + DateField.getText().charAt(3) + DateField.getText().charAt(4)) >= 1)) {
                    DateField.setBorder(new LineBorder(Color.RED));
                    DateCheck.setSelected(false);
                    DateCheck.setText("Invalid");
                    DateExplanation.setText("Invalid Month");
                } else {
                    DateField.setBorder(new LineBorder(Color.GREEN));
                    DateCheck.setSelected(true);
                    DateCheck.setText("Valid");
                    DateExplanation.setText("");
                }
            }

        }

        if (SmartIDButton.isSelected() || PassportButton.isSelected()) {
            if (SmartIDButton.isSelected()) {
                SmartIDButton.setBorder(new LineBorder(Color.GREEN));
                BookingCheck.setSelected(true);
                BookingCheck.setText("Valid");
                BookingExplanation.setText("");
            } else {
                PassportButton.setBorder(new LineBorder(Color.GREEN));
                BookingCheck.setSelected(true);
                BookingCheck.setText("Valid");
                BookingExplanation.setText("");
            }
        } else {
            SmartIDButton.setBorder(new LineBorder(Color.RED));
            PassportButton.setBorder(new LineBorder(Color.RED));
            BookingCheck.setSelected(false);
            BookingCheck.setText("Invalid");
            BookingExplanation.setText("Select either Passport or Smart ID");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_EnterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataValidation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataValidation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AgeCheck;
    private javax.swing.JLabel AgeExplanation;
    private javax.swing.JTextField AgeField;
    private javax.swing.JCheckBox BookingCheck;
    private javax.swing.JLabel BookingExplanation;
    private javax.swing.JCheckBox DateCheck;
    private javax.swing.JLabel DateExplanation;
    private javax.swing.JTextField DateField;
    private javax.swing.JButton EnterButton;
    private javax.swing.JCheckBox IDNumberCheck;
    private javax.swing.JLabel IDNumberExplanation;
    private javax.swing.JTextField IDNumberField;
    private javax.swing.JRadioButton PassportButton;
    private javax.swing.JRadioButton SmartIDButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
